### ISSUE TITLE
Repo unmaintained?

### ISSUE THREAD

**Issue by IronTooch** [ansible-community/awesome-ansible#58]
Is this repo still being maintained? Seems like the addition was four months ago, and there are pull requests outstanding since Dec.

If not, happy to start maintaining at https://github.com/IronTooch/awesome-ansible

**Comment by KeyboardInterrupt** [comment]
Hi, yeah I have just been very busy the last few month or so, If you would like help out with this List, you are welcome to add to it, of course.
If you would like to have an more active role, I could give you necessary permissions to co-maintain / contribute.

If you are good with just contributing via Merge Requests, that is totally fine though! I don't want to burden anyone with responsibilities nor obligations ;) Everyone has enough of those.

**Comment by gundalow** [comment]
Hi,
I look after the Ansible Community Engineering Team at Red Hat, if we could support this, I'd be more than happy to. 
We have https://github.com/ansible-community/ where we have various community maintained projects with various community folks who have commit powers.

I obviously don't want to step on anybody's toes.

**Comment by KeyboardInterrupt** [comment]
Hi @gundalow, as discussed, I am happy to make this repository Part of the ansible-community, I am preparing the Transfer, rn.

**Comment by KeyboardInterrupt** [comment]
As the Repository is

**Comment by IronTooch** [comment]
I'm happy to be added as a co-maintainer, @gundalow , I'd be happy to help over at Ansible Commmuity. Either way, just trying to help!
